### ISSUE TITLE
Question About Crossover 

### ISSUE THREAD

**Issue by cenkakay08** [anas-899/2D-Bin-Packing-with-Genetic-Algorithm#1]
Hi, I have a question about crossover. What do genes represent? Is it the order of the bins or the bins themselves?
One more question :)  
Is it really random when initializing the population or is there a rule for bin sorting?
Have a nice day from Turkey :D

**Comment by anas-899** [comment]
Hi @cenkakay08 
genes represent the bins themselves (every gene have height, width), while the chromosome represent the order of the genes.
I have tested many ways of initialization, like if I initialize the first population when the big genes goes first, another experiment for when the small genes goes first, and ofcourse the obvious one which is the random population. for some problems this ordering plays significant rules, especially when you have many genes with same sizes.

sorry for the late response, this is very old project for me and I am not watching or maintaining it
